### ISSUE TITLE
restore sort by relevance by default

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#129]
with adventist knapsack, we lost the ability to sort by relevance (catalog controller). This should be adventist's default behavior. 

## Testing Instructions

Visit [staging](https://sdapi.adventist-knapsack-staging.notch8.cloud/)
perform an empty catalog search

## Acceptance Criteria
- [ ] ensure the sort is set to relevance by default and that it works

**Comment by ShanaLMoore** [comment]
# QA: Pass ✅ 

https://github.com/scientist-softserv/adventist_knapsack/issues/129

**Comment by KatharineV** [comment]
Confirmed the relevance search is present as the default on Knapsack staging and production for ADL
