### ISSUE TITLE
Remove display of public tag

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#152]
# Summary

Remove the display of tags on the work show page

![image](https://github.com/scientist-softserv/adventist_knapsack/assets/10081604/55a5b732-b2e4-4539-af2e-ce4810571d1d)

# Acceptance Criteria

- [ ] tags like 'public' should not be rendered to the user

# Testing Instructions

- [ ] Parity with pre knapsack cut over (ignore the red circle but notice that no tags display)

![image](https://github.com/scientist-softserv/adventist_knapsack/assets/10081604/10aa533d-8a4f-4aac-97ea-b9bb18985ba5)

# Notes

ref: 
- https://github.com/scientist-softserv/adventist-dl/issues/747#issuecomment-2063919386

![Image](https://github.com/scientist-softserv/adventist_knapsack/assets/10081604/37a6f47a-e302-487b-95cc-06e70177f94c)

related?
- https://github.com/scientist-softserv/adventist-dl/issues/23
- https://gitlab.com/notch8/adventist-dl/-/issues/82 (it looks like this was previously implemented via css changes. We still have this [code](https://github.com/scientist-softserv/adventist_knapsack/blob/main/app/assets/stylesheets/adl-overrides/adl-overrides.scss#L455-L460) in the knapsack but perhaps the class names changed)

![Image](https://github.com/scientist-softserv/adventist_knapsack/assets/10081604/16910d6e-639e-4193-b8cb-017cdce0812b)

**Comment by KatharineV** [comment]
The public tag is no longer showing on ADL or SDAPI production. Thank you!

**Comment by ShanaLMoore** [comment]
# QA: Fail ❌ 

This is hiding more than the title badges



![Image](https://github.com/scientist-softserv/adventist_knapsack/assets/10081604/f8cdaba2-afed-48a8-adc2-b377b4ab8b9f)
