### ISSUE TITLE
SDAPI: Script to find the identifiers of all records that made it into their hyku site

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist_knapsack#194]
## Summary
When they migrated their works to hyku, there ended up being ~20,000 records missing (there's 750,000 on the old site and only 722,000 in hyku). Katharine tried to export all of the records/their metadata that are in her hyku site, to get their identifiers so she could try to find those records that are missing. It is taking too long, can we run a script to find all of those records? This is for the SDAPI tenant

## Acceptance Criteria
- [x] Script to find the identifiers of all records that made it into their hyku site has been run
- [x] ID's are given to Katharine [identifiers.txt](https://github.com/scientist-softserv/adventist-dl/files/14425388/identifiers.txt)

**Comment by KatharineV** [comment]
This was done and I'm sorry I never realized I should close the ticket. Thank you for doing this!
