### ISSUE TITLE
Spike: File attachment issues (production)

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist_knapsack#680]
## Summary
https://assaydepot.slack.com/archives/C0313NJV9PE/p1718979488041259

This is a quick note. I can expand on this later. We have a critical problem in the repository. We cannot add files to new works through the following paths: 

1. CSV with related_url
2. CSV with zipped files
3. UI with drag and drop file attachment

Importers in Bulkrax are failing and when they succeed they import metadata and fail to appropriately attach files. The failures recently have declared that no identifier is present when the CSV definitely has identifiers and Shana even double-checked and couldn't find anything wrong with the CSV. I also stripped the data of any hidden characters as best I could by dropping it into Notepad, importing into OpenRefine and then exporting back out, etc. 

Importer with related_url that failed: https://adl.b2.adventistdigitallibrary.org/importers/380?locale=en

Importer with zipped files that created works without attaching files: https://adl.b2.adventistdigitallibrary.org/importers/381?locale=en

UI work I just created that is acting like the file doesn't exist (may remedy itself if this is just a lag issue--everything has been INCREDIBLY SLOW lately, so maybe that's the problem here? will check later) 
https://adl.b2.adventistdigitallibrary.org/concern/images/p810063_ou_home_on_the_hillside_dansville_lithograph?locale=en

## Acceptance Criteria
- [ ] Follow up tickets for the fix has been created

**Comment by KatharineV** [comment]
The UI work is not loading at all today. See screenshot below with the error message I see:



![Image](https://github.com/scientist-softserv/adventist_knapsack/assets/118196520/27c696f3-12f5-474e-b404-f2dd34c03dbc)

**Comment by jillpe** [comment]
Could be related to the UTK javascript issue

**Comment by kirkkwang** [comment]
@KatharineV 
we're working through these issues, here's our findings so far

1. This seems to be the issue of the CSV's URL's using `+` which gets stripped out and replaced with a ` ` (space) character.  We've actually seen this before in this thread https://assaydepot.slack.com/archives/C0313NJV9PE/p1709017438515919?thread_ts=1708699548.345299&cid=C0313NJV9PE
The workaround right now is just to replace the `+` with `%20` instead.

2.  The link to importer 381 shows that it's a csv, so no zipped files that I found.  Do you have another one to reference?

3.  I have not been able to replicate this.  Do you think we can set up a time for a demo to see how you're running into this?

**Comment by KatharineV** [comment]
@kirkkwang Thanks for these notes. 
1. Your reminder about the + makes sense. When the CSV was failing for no reason I could detect, and it was throwing that "no identifier" error that I recognized, I felt sure there was some simple error obstructing Bulkrax, but I couldn't see it. You caught it! Thank you. 

2. It's been a while, so I can't be sure what my workflow was. If you don't see zipped files, I probably grabbed the wrong CSV when I was running dozens of tests around the time I created this ticket. Sorry! I've updated the importer now, and I used the intended CSV and files, zipped together. The importer worked before because it was just bringing in metadata. Now Importer 381 says it has failed for a missing identifier, but the works are marked as pending, so I don't know what we'll see. https://adl.b2.adventistdigitallibrary.org/importers/381?locale=en 

3. I can't access the work that is linked earlier in this ticket, so I guess it failed on a very fundamental level. It's just an error message now. 
Today, I tested uploading a JPEG through the UI on staging, and it worked. https://testing.s2.adventistdigitallibrary.org/concern/images/75490c16-b841-49f2-8530-498a7b37546f?locale=en 
I also tried uploading files through the UI on production, and results are mixed. PDFs imported to the SDAPI tenant today are present: https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/journal_of_adventist_mission_studies_2022_02_66_80_symbols_from_revelation
A TIFF added to a new work on the ADL tenant is not showing any files attached: https://adl.b2.adventistdigitallibrary.org/concern/images/73c284c2-9b15-425b-9d10-905d39076431?locale=en 
Perhaps the issues through the UI are tenant-specific?

**Comment by ShanaLMoore** [comment]
@KatharineV For point number 2 would you be able to provide a sample zip (tmp/imports/adl/381_20240614180020_650/BOX 010 csv to tsv_to_zip_6171-6189.zip) used for this [importer](https://adl.b2.adventistdigitallibrary.org/importers/381/edit?locale=en)?

**Comment by KatharineV** [comment]
Yes, here's a WeTransfer link that contains the zip I put in yesterday:  https://we.tl/t-GU29JxaNAD.

And here are the CSV and files separately via DropBox: https://www.dropbox.com/scl/fo/mipr9ujtltqgxempmgdrp/APxFmQU3El5vlFC_pRX9zJI?rlkey=9ah5y2c0j6zeoctfeitsakdn8&st=05dt7nik&dl=0
________________________________

**Comment by ShanaLMoore** [comment]
# Notes for point 2:  Error: StandardError - Missing at least one required element, missing element(s) are: identifier issue when the CSV contains the identifier column.

Debugging from console: 
```ruby
Comparing "identifier" with "identifier"
Bytes do not match: "identifier" != "identifier"
Expected bytes: [105, 100, 101, 110, 116, 105, 102, 105, 101, 114]
Actual bytes: [239, 187, 191, 105, 100, 101, 110, 116, 105, 102, 105, 101, 114]
```

The difference in bytes indicates that the identifier key in your data contains a Byte Order Mark (BOM) character (represented by the byte sequence [239, 187, 191]) at the beginning. This can happen if the CSV file was saved with a BOM, which is common for UTF-8 encoded files.

I'll see about implementing a fix to detect and remove bom characters even though I thought Jeremy did this already 🤔

**Comment by ShanaLMoore** [comment]
@KatharineV Could you attach the file used for [this work](https://adl.b2.adventistdigitallibrary.org/concern/images/73c284c2-9b15-425b-9d10-905d39076431?locale=en)?

**Comment by KatharineV** [comment]
Absolutely. Here's the TIFF via WeTransfer: https://we.tl/t-Wjxoct46hO

**Comment by ShanaLMoore** [comment]
Heads Up - I'm going to divide this issue into separate tickets. 

# TASKS

- [ ] https://github.com/scientist-softserv/adventist_knapsack/issues/684
