### ISSUE TITLE
🐛 Staging- No such file or directory @ rb_sysopen

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#691]
# Summary

We are receiving a strange error when importing on staging: 

```
 Error: Errno::ENOENT - No such file or directory @ rb_sysopen - tmp/imports/adl/261_20240712171903/BOX 010 csv to tsv_to_zip_6171-6189.zip
```

How could it complete two of them but then decide that it can't find the file? 

Steps to reproduce:

STAGING: https://adl.s2.adventistdigitallibrary.org/importers/260?locale=en

Sample file: [DOWNLOAD](https://wetransfer.com/downloads/98a3ec1d04f581239ab2998df8cbad9920240904171732/7190e2)

# Acceptance Criteria

- [ ] A user should be able to import the sample file without errors

# Screenshots or Video

![Image](https://github.com/user-attachments/assets/c5213c20-37f3-4ac4-b574-5318156cdfa7)

# Testing Instructions

To be filled in by dev

# Notes

**Comment by jillpe** [comment]
This was before valkyrization - should be resolved with that. Need to verify when valkyrization is deployed

**Comment by ShanaLMoore** [comment]
TODO: Re run [this specific importe](https://adl.s2.adventistdigitallibrary.org/importers/260?locale=en)r to test if this is still occurring on a valkyrie application

**Comment by ShanaLMoore** [comment]
cc @sjproctor I think I just saw a similar error happening for pals.

**Comment by KatharineV** [comment]
New WeTransfer link good for 3 days from 9/4/2024

Contains CSV and zipped files from the importer at the top of the ticket

https://we.tl/t-fcitB3vSOs

**Comment by ShanaLMoore** [comment]
putting a blocked label on this until the bulkrax issue is resolved. LaRita is working on the fix now.

**Comment by ShanaLMoore** [comment]
Closing. I re ran the reported [problematic importer](https://adl.s2.adventistdigitallibrary.org/importers/260?locale=en) now that valkyrie is in place and the importer succeeded. We'll create another ticket if this issue is seen again. 

![image](https://github.com/user-attachments/assets/bf39e07c-e014-4d74-8e12-94fdee8373df)
