### ISSUE TITLE
🐛 Bulkrax: OAI Imports Fail

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#723]
# Summary

I attempted to import the following: 

![Image](https://github.com/user-attachments/assets/5c9eb6d4-3c29-40cd-98b6-742f6ed91c13)

I can see that the import failed: 

![Image](https://github.com/user-attachments/assets/12803241-cd1f-47bb-a165-c28965cb5110)

~However, when I click on the importer I get this error:~ 
Update: (resolved by [this PR](https://github.com/samvera/bulkrax/pull/966))

![Image](https://github.com/user-attachments/assets/f972ede5-b105-45c8-a8c3-9dd8b04b3c8d)

The actual error: 

![Image](https://github.com/user-attachments/assets/64ee9a68-1421-4b3e-82c5-51f7e79e8214)

![Image](https://github.com/user-attachments/assets/2ea53f81-daf4-4a41-a7f8-9a72fe0cb250)

# Acceptance Criteria

- [ ] A user should be able to import from an OAI feed

# Testing Instructions

Recreate the attempted importer (see screenshot in the summary section). set the limit to 10.
The importer should complete without errors.

# Notes

The oai importer appears to be broken on [staging](https://demo.s2.adventistdigitallibrary.org/importers/5?locale=en) too, pre valkyrie

**Comment by ShanaLMoore** [comment]
Because Rob already has oai jobs enqueue, the concern to create a new importer can be addressed later so I'll remove high priority from this ticket.

**Comment by ShanaLMoore** [comment]
from bulkrax branch handle-remote-files-for-valkyrie, the importer succeeds now. However the labels look wrong. 



![Image](https://github.com/user-attachments/assets/45feab9a-b563-4b3e-a820-def50e32994a)



### Staging: 


![Image](https://github.com/user-attachments/assets/7c69b10c-825f-41c8-aec9-c48fe1ea93ae)




### Local: 


![Image](https://github.com/user-attachments/assets/2372f127-4e04-479b-8b9f-35b36e255e91)

**Comment by sjproctor** [comment]
I think this worked for me.

![Image](https://github.com/user-attachments/assets/c7ccaa70-a345-4868-94e4-d8c80f9ed473)
