### ISSUE TITLE
:unicorn: Spike: Confirm that iiif print split works

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#725]
# Summary

Now that adventist has been valkyrized, try importing a multi page pdf with iiif print configurations turned on. See if it properly splits the works. 

# Acceptance Criteria

- [x] Create separate tickets if there are issues found.

# Screenshots or Video

# Testing Instructions

# Notes
Issues found (and decorated in Adventist code until IiifPrint is fixed):
- [ ] #728
- [ ] #729
- [ ] #730

**Comment by ShanaLMoore** [comment]
this needs to be tested on staging

**Comment by laritakr** [comment]
Issues found:
- [ ] Derivative Rodeo splitter expects to receive file_set
