### ISSUE TITLE
Iiif manifest is not generating correctly for universal viewer

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#730]
# Story

When PDF files are split into multiple pages, they are expected to be viewable and searchable in the universal viewer. The manifest is not loading the canvas correctly.

Commit https://github.com/scientist-softserv/adventist_knapsack/pull/693/commits/630c7e54ad7de3b8aefb86b7eb11e061e264a873 introduced lonely operators which bypass the errors that were happening. Removing the lonely operators should allow finding what is missing.

# Acceptance Criteria

- [ ] Images appear appropriately in universal Viewer

# Screenshots / Video

<details>
<summary>Manifest that is not working</summary>

```
{
"@context": [
"http://www.w3.org/ns/anno.jsonld",
"http://iiif.io/api/presentation/3/context.json"
],
"type": "Manifest",
"id": "https://cat.hyku.test/concern/datasets/a85de229-b43e-4d7f-816c-d4c57269a509/manifest",
"label": {
"none": [
"Another split attempt"
]
},
"rights": "http://rightsstatements.org/vocab/InC-EDU/1.0/",
"metadata": [
{
"label": {
"en": [
"Rights statement"
]
},
"value": {
"none": [
"<a href='http://rightsstatements.org/vocab/InC-EDU/1.0/'>In Copyright - Educational Use Permitted</a>"
]
}
}
],
"service": [
{
"@context": "http://iiif.io/api/search/1/context.json",
"profile": "http://iiif.io/api/search/1/search",
"label": "Search within this manifest",
"type": "SearchService1",
"id": "https://cat.hyku.test/catalog/a85de229-b43e-4d7f-816c-d4c57269a509/iiif_search"
}
],
"items": [],
"viewingHint": "paged",
"rendering": [
{
"@id": "https://cat.hyku.test/downloads/f2bf12d9-eaaa-4e7d-a878-b7fe5fa8e28e",
"label": null,
"format": "application/pdf"
}
]
}
```

</details>

# Testing Instructions and Sample Files

- Ensure the tenant is set up to use the universal viewer.
- Find or create a work resource with image files attached
- [ ] The images appear in the universal viewer.

# Note
- [ ] https://github.com/scientist-softserv/palni_palci_knapsack/issues/111
 if it is a bug beyond this app, the fix should be moved to IiifPrint)

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ❌ NEEDS REWORK

TESTED ON [STAGING](https://adl.s2.adventistdigitallibrary.org/concern/images/p006179_union_college_german_iii_class_1909?locale=en)

The image does not display in the UV even though it's attached to the work



![Image](https://github.com/user-attachments/assets/4ef1a6bf-544b-4092-ad04-5f7795d407ce)

**Comment by laritakr** [comment]
Need to rework how the viewers show.

Based on flipper setting and split status, we see:

- Default viewer PDF.js, no split >> shows pdfs viewer
- Default viewer: UV, no split >> uses representative_media partial and UV - black box because no split
- Default viewer PDF.js, split into child works, >> no viewer, shows default thumbnail
- Default viewer: UV, split >> uses UV

**Comment by ShanaLMoore** [comment]
This issue will be covered and tested in #760
