### ISSUE TITLE
🐛 UV doesn't load

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#747]
# Summary

Tested on staging, the UV is not loading even though the work has a file set attached. (tiff)

/manifest.json produces a 500 internal server error

related: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/786

# Acceptance Criteria

- [ ] The UV should display 

# Screenshots or Video

# Testing Instructions
In [staging](https://adl.s2.adventistdigitallibrary.org/concern/images/p006178_union_college_faculty_and_student_group_1909?locale=en), visit a work with an attached file

# Notes

**Comment by laritakr** [comment]
# QA RESULTS: PASS ✅

Tiff file correctly displays in UV.

[Tested on staging](https://adl.s2.adventistdigitallibrary.org/concern/images/p006178_union_college_faculty_and_student_group_1909?locale=en)
