### ISSUE TITLE
Script to migrate admin sets and collections - this is a Hyku thing

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#773]
Script should cycle through each tenant to load and save each admin set and collection

Below is sample code for admin sets. Collections will vary slightly.
Note: this gets all defined admin set classes. We probably want to use only ActiveFedora classes.
```
models = Hyrax::ModelRegistry.admin_set_classes
    unique_models = []
    models.each do |model|
      unique_models << Wings::ModelRegistry.lookup(model)
    end

    unique_models.uniq.each do |model|
      admin_sets = Hyrax.query_service.find_all_of_model(model:)
      admin_sets.each do |as|
        fm = AdminSetResourceForm.new(resource: as)
        converted = Hyrax.persister.save(resource: fm)
        Hyrax.index_adapter.save(resource: converted)
      end
    end
```

## TODO: 
- [ ] add collection reindex to script as the final step
- [ ] update project submodule once merged

## NOTES

ref: 
- https://github.com/samvera/hyku/blob/main/app/jobs/migrate_resources_job.rb

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ⚠ PENDING

TESTED ON ADVENTIST

command: `rake migrate_collections`

produced: 



![Image](https://github.com/user-attachments/assets/07d55f27-7e79-4a22-9ba0-591a8d3806d8)

**Comment by ShanaLMoore** [comment]
# QA RESULTS: ✅ PASS

To confirm that all collections and adminsets got converted,  find all collections in af and compare to collections in the resource table. do they all exist? every record in af should be in the resource table,

There was a weird behavior where two of the collections didn't get indexed for some reason. This manifested itself in such a way that I got an unauthorized message when trying to view it directly, but i could find the record in the rails console. reindexing the collection resource resolved this so it may be a good idea to run the collection reindex task afterwards, just in case.

**Comment by ShanaLMoore** [comment]
TODO: run script in staging to confirm per @laritakr

**Comment by ShanaLMoore** [comment]
Rob has made alterations to this job after testing it on Pals. 

ref: 
- https://github.com/samvera/hyku/commit/43a2d1e07cc28eae48f2c93af639f77ed1e013a3
