### ISSUE TITLE
Valkyrie: Bulkrax not adding to collections

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist_knapsack#775]
# Summary

I added three new works to ADL staging via Bulkrax. The works are assigned to a collection and a subcollection that exist in Staging, and I confirmed that the Hyku IDs are right in the CSV used for the upload. GoodJobs shows zero tasks running, but the works are not showing the collections in the Relations list at the bottom of the work pages, and they don't show in the collections either. 

Importer: https://adl.s2.adventistdigitallibrary.org/importers/310?locale=en

Collection: https://adl.s2.adventistdigitallibrary.org/dashboard/collections/9c5feb14-7c90-499f-aa4e-ea5cf40baf2d?locale=en
Subcollection: https://adl.s2.adventistdigitallibrary.org/dashboard/collections/ebbab001-fd0c-40f2-ab26-eebab8808392?locale=en 

# Acceptance Criteria

- [ ] A user should be able to attach work through collections via bulkrax

# Screenshots or Video

# Testing Instructions

To be filled out by dev

# Notes

**Comment by ShanaLMoore** [comment]
@KatharineV I haven't tried this locally yet, but I downloaded the file from the importer and noticed two columns that I don't think would work for establishing relationships. I was expecting to see a parents column. Is there a reason for these particular headers and does this import work for production?



![Image](https://github.com/user-attachments/assets/8a7ccec3-3104-4774-9688-a3c3084a6696)





[BOX 001 - w spaces - for Valkyrie staging(1).csv](https://github.com/user-attachments/files/16899162/BOX.001.-.w.spaces.-.for.Valkyrie.staging.1.csv)



![Image](https://github.com/user-attachments/assets/8130901e-b4e0-4545-902d-c54ef59ec0f9)

**Comment by KatharineV** [comment]
@ShanaLMoore you're right and those columns have placeholder titles. I caught and corrected them before I ran the importer that eventually worked. If those placeholders (that I missed) were the reason the CSV failed, I would have liked Bulkrax to flag the improper headings rather than telling me there was an identifier problem, since obviously that was false flag that sent me off in the wrong direction. 

I will also add that I'm only 80% confident that these are the exact same CSVs that I tried to share previously via that WeTransfer link. I'm sorry. Lots of time has passed since I first tried to share the files, I created soooooo many versions of this particular CSV in an effort to fix it (which is how I eventually did catch that bad column header), and my attempt to retrace my steps today may have been wrong.

**Comment by ShanaLMoore** [comment]
totally understand. Mind if I close this issue then? What you're asking for is header validation which would be better expressed as a separate ticket/issue @KatharineV

**Comment by KatharineV** [comment]
Yes, I understand. I can close with this comment, if that's helpful. If there's another non-human-error bug that causes the "identifier not found" problem, then I'm sure it will show itself again someday and I can open a new, more accurate ticket.
