### ISSUE TITLE
Disable split when PDF.js is enabled

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#779]
# Summary

See how PDF.js was implemented for ATLA. Kirk. may be the best point of contact. 

When PDF.js is turned on, we want to disable iiif split. 

# Acceptance Criteria

- [ ] When PDF.js is turned on, PDFs should not split

# Screenshots or Video

tested on: [STAGING](https://demo.s2.adventistdigitallibrary.org/concern/published_works/3111a4fa-19d4-41d6-af4e-4d16b8ea1a2c?locale=en)

![Image](https://github.com/user-attachments/assets/25f6058d-496e-4d6b-8920-a5406cba7785)

# Testing Instructions

- Enabled PDF.js in the admin dashboard features settings. 
- either through via bulkrax or manually, attach a multi page pdf file to a new work and save. 
- Make sure jobs complete. If so, child works from iiif split should not have been created. 

# Notes

breadcrumbs c/o LaRita: 
<img width="374" alt="image" src="https://github.com/user-attachments/assets/8f1bf597-5548-4273-ae06-da1f2d78571e">

**Comment by laritakr** [comment]
This should be done by adding the check to the pdf.js flag into the adventist splitter.
