### ISSUE TITLE
Some form data persisting `[""]` instead of `[]` for blank entries

### ISSUE THREAD

**Issue by sjproctor** [scientist-softserv/adventist_knapsack#807]
## Summary
Data fields that appear blank are rendering on the works show page. This is because at some point during form submission some attributes get assigned `[""]` if there is no data. 

The commit `17489e60223a00d62b36525adc66c09ce1fa630a` on Adventist Knapsack provided a temporary solution for the client.

The fields are:
- Date issued
- Publication date
- Publication status
- Issue
- Date submitted
- Date accepted
- Date available

## Acceptance Criteria
- [x] If fields are blank they do not display

## Testing Instructions
- Revert the code in `app/renderers/hyrax/renderers/attribute_renderer.rb` from `return markup if Array.wrap(values).first.blank? && !options[:include_empty]` to `return markup if values.blank? && !options[:include_empty]`
- Create a work with only the required metadata. Visit its show page.
- Blank metadata properties should not be displayed. 

## Notes
This appears to happen most often on data values.
Ref: https://github.com/scientist-softserv/adventist_knapsack/issues/771

**Comment by sjproctor** [comment]
Possibly related: When editing a work, fields that can contain multiple inputs often have a blank second value added.
![Image](https://github.com/user-attachments/assets/6eb22be2-ed15-48cd-8ee2-27039461f731)

**Comment by ShanaLMoore** [comment]
Issue seems to be happening [here](https://github.com/samvera/hyrax/blob/main/app/controllers/concerns/hyrax/works_controller_behavior.rb#L196). 

@sjproctor  to attach screenshot of params. Form looks as expected before this point.

**Comment by sjproctor** [comment]
`app/samvera/hyrax-webapp/gems/hyrax/app/controllers/concerns/hyrax/works_controller_behavior.rb` 
- form looks correct
![Image](https://github.com/user-attachments/assets/c92f6485-c0f5-4049-9d44-27b31cc8bb6e)
- action looks correct
![Image](https://github.com/user-attachments/assets/a2c56040-2a3c-4a5d-8328-97fcac539699)
- params are not correct
![Image](https://github.com/user-attachments/assets/6bad87be-53b0-456e-835c-1f6010e3f243)

**Comment by kirkkwang** [comment]
In Hyrax the params also get populated with `[""]` or `""`, so I'm thinking something is happening in the action

**Comment by sjproctor** [comment]
This problem is being addressed in https://github.com/scientist-softserv/adventist_knapsack/issues/771
