### ISSUE TITLE
🦄 SPIKE: Batch deleting resources works doesn't appear to be working

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#813]
# Story

- Using OAI importer, import a work which splits via IiifPrint (this will ensure it uses slugs)
- In the dashboard, select multiple child works to delete. I changed the page to display 100 works, and selected everything on the first page. ([Deleting a work does not delete its children](https://github.com/scientist-softserv/adventist_knapsack/issues/739) so this is the only way to remove them)

In my test, this caused many resource loads that looked as if they were loading the same resources repeatedly, and spun for a very long time. I ended up restarting my web container and am unsure if/how many child works were removed, if any.

```
  CACHE Valkyrie::Persistence::Postgres::ORM::Resource Load (0.0ms)          SELECT member.* FROM orm_resources a,
        jsonb_array_elements(a.metadata->'member_ids') WITH ORDINALITY AS b(member, member_pos)
        JOIN orm_resources member ON (b.member->>'id')::text = member.id WHERE a.id = '828cd079-e937-4ed9-804e-5f3bb12f8f29'
        ORDER BY b.member_pos

  Valkyrie::Persistence::Postgres::ORM::Resource Load (0.4ms)          SELECT member.* FROM orm_resources a,
        jsonb_array_elements(a.metadata->'member_ids') WITH ORDINALITY AS b(member, member_pos)
        JOIN orm_resources member ON (b.member->>'id')::text = member.id WHERE a.id = '7e6aefc8-7d40-4d12-bb84-3e0c5dc614ac'
        ORDER BY b.member_pos

  CACHE Valkyrie::Persistence::Postgres::ORM::Resource Load (0.0ms)          SELECT member.* FROM orm_resources a,
        jsonb_array_elements(a.metadata->'member_ids') WITH ORDINALITY AS b(member, member_pos)
        JOIN orm_resources member ON (b.member->>'id')::text = member.id WHERE a.id = '7e6aefc8-7d40-4d12-bb84-3e0c5dc614ac'
        ORDER BY b.member_pos

  Valkyrie::Persistence::Postgres::ORM::Resource Load (0.5ms)          SELECT member.* FROM orm_resources a,
        jsonb_array_elements(a.metadata->'member_ids') WITH ORDINALITY AS b(member, member_pos)
        JOIN orm_resources member ON (b.member->>'id')::text = member.id WHERE a.id = '19014c59-dc53-4291-8125-122befe76835'
```

(Note that re-importing using the delete option does not work as far as I am aware. I always delete the works before retrying.)
 
# Acceptance Criteria

- [ ] Able to batch destroy child works from the dashboard

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

Do an OAI import using the following info. These are large PDFs, so limit to 1 or so works. You can use a small offset number to avoid duplicate works if needed.
**base_url**: http://oai.adventistdigitallibrary.org/OAI-script
**metadata_prefix:** oai_adl
**set:** adl:thesis

On the works index page, pick the option to view 100 at a time. select all and click the delete selection button. 

# Notes

**Comment by ShanaLMoore** [comment]
I can confirm that deleting 100 records seems to be taking too long, and may even be stuck.

**Comment by ShanaLMoore** [comment]
UPDATE: the batch delete finally completed successfully. I now only have 132 works left. It just took a long time to complete this action.

**Comment by ShanaLMoore** [comment]
cc @laritakr jk. let me try to follow the actual instructions. We want to test this with slugs huh? 

Standby :)

**Comment by ShanaLMoore** [comment]
Retested by using an OAI import as instructed above. ⚠ PENDING

I noticed the child works don't have slugs though. 

## BEFORE 
start time: 3:22PM



## AFTER
