### ISSUE TITLE
Sort out metadata fields

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist_knapsack#822]
# Summary

related: 
- #771 

ref: 
- https://github.com/samvera/hyku/pull/2341#issuecomment-2364493546

We have changed metadata from multiple to singular values. Will this cause a problem when converting prod data into valkyrie resources? Will we lose data?

For example, what if prod has multiple values but when we reindex, it should only have one? 

This task is to look at each work type in prod and compare it to our metadata yaml definitions to make sure we match as much as possible. 

# Acceptance Criteria

- [ ] This ticket can be closed after the following metadata yaml files have been verified/completed: 
  - [ ] adl_metadata.yaml 
  - [ ] collection_resource.yaml
  - [ ] conference_item_resource.yaml
  - [ ] dataset_resource.yaml
  - [ ] exam_paper_resource.yaml
  - [ ] generic_work_resource.yaml
  - [ ] image_resource.yaml
  - [ ] journal_article_resource.yaml
  - [ ] published_work_resource.yaml
  - [ ] thesis_resource.yaml

# Testing Instructions

**NOTE: This is an internal ticket that shouldn't require a review from the client**

### CREATE

Fill out all the metadata fields

create each work type and verify that you can successfully save

  - [x] collection_resource
  - [x] conference_item_resource
  - [x] dataset_resource
  - [x] exam_paper_resource
  - [x] generic_work_resource
  - [x] image_resource
  - [x] journal_article_resource
  - [x] published_work_resource
  - [x] thesis_resource

### EDIT

edit each work type and verify that you can successfully save

  - [x] collection_resource
  - [x] conference_item_resource
  - [x] dataset_resource
  - [x] exam_paper_resource
  - [x] generic_work_resource
  - [x] image_resource
  - [x] journal_article_resource
  - [x] published_work_resource
  - [x] thesis_resource

**Comment by ShanaLMoore** [comment]
Audit completed by Sarah and Kirk. They've confirmed that they're still able to edit and save each work type after making these changes. 

![Image](https://github.com/user-attachments/assets/2d4b62c4-dafd-40ea-8956-22a76cc9e694)

**Comment by ShanaLMoore** [comment]
TODO: 

### EDIT

edit each work type and verify that you can successfully save

  - [ ] adl_metadata 
  - [ ] collection_resource
  - [ ] conference_item_resource
  - [ ] dataset_resource
  - [ ] exam_paper_resource
  - [ ] generic_work_resource
  - [ ] image_resource
  - [ ] journal_article_resource
  - [ ] published_work_resource
  - [ ] thesis_resource

### CREATE

create each work type and verify that you can successfully save

  - [ ] adl_metadata 
  - [ ] collection_resource
  - [ ] conference_item_resource
  - [ ] dataset_resource
  - [ ] exam_paper_resource
  - [ ] generic_work_resource
  - [ ] image_resource
  - [ ] journal_article_resource
  - [ ] published_work_resource
  - [ ] thesis_resource

**Comment by ShanaLMoore** [comment]
Katharine reported an inability to edit a Collection [here](https://github.com/scientist-softserv/adventist_knapsack/issues/777#issuecomment-2375106448). 

The error says: 

`2024-09-25T22:39:58.658842776Z Error: ERROR: [doc=851b4393-f9d1-4fa1-b1d9-31bf589c8fff] Error adding field 'issue_number_isim'='Issue' msg=For input string: "Issue"`

which was changed in the [PR](https://github.com/scientist-softserv/adventist_knapsack/pull/824/files#diff-01e83bb796f51e0ba3fa5d701355b10b71f36b850224416259b602179656f6b0R113) of this work.

**Comment by sjproctor** [comment]
```
concerns = Hyrax.config.curation_concerns.map{ |c| "#{c}Resource".safe_constantize } << CollectionResource

concerns.each do |concern|
  works = Hyrax.query_service.find_all_of_model(model: concern)
  works.each do |work|
    next unless work.singleton_class.name.nil?
    next unless work.creator.last.blank?
    next if work.id == 'c7019db2-067c-403c-95b0-11c06715d5ca'
    array = work.creator
    array.pop
    work.creator = array
    work.save
  end
end
```

**Comment by laritakr** [comment]
Closing... QA will be handled via #777 ([see comment](https://github.com/scientist-softserv/adventist_knapsack/issues/777#issuecomment-2384037879))
