### ISSUE TITLE
🐛 Resolve error 'hyrax_parent_active_fedora_base_path'

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#836]
# Story

In the SDAPI tenant, there are some works that were split prior to valkyrization. When trying to view them, they throw an error. 
Need to identify the reason for the failure and make appropriate corrections.

dashboard query: https://sdapi.s2.adventistdigitallibrary.org/dashboard/works?locale=en&page=192&per_page=100
one of works with error: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/pur_2010_feb_pacific_union_recorder_february_2010?locale=en

# Acceptance Criteria

- [ ] Works can be viewed without error

# Screenshots / Video

<details>
<summary></summary>

![Image](https://github.com/user-attachments/assets/9f128581-6f79-4eed-8bc0-c1a3e5b0503a)

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by ShanaLMoore** [comment]
This may be related to ticket: https://github.com/scientist-softserv/adventist_knapsack/issues/839

**Comment by ShanaLMoore** [comment]
blocked by #851

**Comment by laritakr** [comment]
We have identified this as an indexing issue with ordered members. We were able to fix the issue by finding the work and then running 3 reindex commands over it: 
```
w = JournalArticle.find('pur_2010_feb_pacific_union_recorder_february_2010')
w.members.each{|m| m.update_index}
w.list_source.update_index
w.update_index
```

**Comment by laritakr** [comment]
Closing with the above documentation in case we identify further problem works.

**Comment by laritakr** [comment]
The above item appears to have some bad data... Fedora has an access control relationship to an object that doesn't exist, but I'm unsure what object is actually missing. I am going to try to remove all of the members and re-attach the pdf and hope it works this time.

**Comment by laritakr** [comment]
Migrating the above item got it working again. The PDF fileset migration failed with an empty file error, and I can not find the fileset now. But the viewer on the parent work still shows all the children.
