### ISSUE TITLE
Admin set issue when depositing new work through collection

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist_knapsack#842]
While testing Valkyrie in staging, I discovered that choosing "deposit new work through this collection" from a collection's dashboard page has a bug in the creation process. Where you select your work type, you should also have the option to select the admin set. That option is inoperable, and the new work you choose is automatically assigned to an admin set. When I tested the process, it chose the last admin set listed alphabetically. There doesn't appear to be any reason why this set was chosen.

Collection I tested: https://adl.s2.adventistdigitallibrary.org/collections/ed64bf09-7142-4251-9abe-698cc6568a10?locale=en
Work I created, which was randomly assigned to an admin set: https://adl.s2.adventistdigitallibrary.org/concern/images/c0158d87-8ae8-4fff-9e93-ca5219abd953?locale=en

Note how the deposit into admin set option has no dropdown
![Image](https://github.com/user-attachments/assets/bfe90c4c-78f3-4cb0-84fa-cbc4935627d4)

Creating a new work from the Works page on dashboard does give the deposit dropdown
![Image](https://github.com/user-attachments/assets/75c3d178-7617-40d5-b320-48485603325b)

**Comment by laritakr** [comment]
Closing as this issue is no longer happening.
