### ISSUE TITLE
Migrating a file does not migrate all of its characterization

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist_knapsack#845]
# Story

When you edit & save an individual file set, it breaks the universal viewer. This is because it loses some of the characterization values. (This was just recently discovered because migrating a work apparently does not migrate its individual filesets even though it should.)

This is apparently a hyrax bug.

# Acceptance Criteria

- [ ] Files migrate appropriately, and are able to be viewed in the universal viewer.

# Screenshots / Video

<details>
<summary></summary>

## Migrated file
![Screenshot 2024-10-02 at 4 03 49 PM](https://github.com/user-attachments/assets/b2fbea52-7354-4991-9bbc-d1df5c117314)

## Unmigrated file
![Screenshot 2024-10-02 at 4 03 38 PM](https://github.com/user-attachments/assets/20ac70ca-45f4-4cdd-a41b-74b175b2aa5a)

## Error message
![Screenshot 2024-10-02 at 4 06 14 PM](https://github.com/user-attachments/assets/af73c84d-f468-428c-8620-6f5e1c031de8)

</details>

# Testing Instructions and Sample Files

Open a Fedora fileset with an image, and select edit, then save. 

Find a fedora fileset by going to a work created before 2024, open one of the child works, and then open the fileset (verify the date is also before valkyrie work to ensure that it hasn't already been migrated). Edit and save that fileset.

- [ ] Image characterization values should still be present.
- [ ] Image should still appear in universal viewer.

Note that editing a child work does not migrate the file set... you have to edit the actual fileset.
Also, once a file set is migrated, the parent work's viewer will not show the documents until the parent work is also migrated.

# Notes

**Comment by laritakr** [comment]
Fixed in hyrax via https://github.com/samvera/hyrax/pull/6914
Updated hyrax in hyku via https://github.com/samvera/hyku/pull/2360

**Comment by ShanaLMoore** [comment]
TODO: QA and close cc @laritakr

**Comment by laritakr** [comment]
# QA Results: ❌ 

Saving a file and lazy migrating did not migrate all characterization attributes from the views. It is unknown whether the view doesn't find them or if they just didn't migrate.

<details>
<summary>Screenshots</summary>

### Pdf file set before migration
<img width="1225" alt="Screenshot 2024-10-25 at 12 58 25 PM" src="https://github.com/user-attachments/assets/91b8acbf-62b5-4b4e-99a4-7453c081fae0">


### Pdf file set after m
<img width="1230" alt="Screenshot 2024-10-25 at 12 59 12 PM" src="https://github.com/user-attachments/assets/2435e27d-0e73-4b1a-8909-c5e3e296e261">
igration

### Jpg file set b
<img width="1160" alt="Screenshot 2024-10-25 at 1 04 21 PM" src="https://github.com/user-attachments/assets/1b29e8ef-c65a-484d-8f49-6abb685c9329">
efore migration

### Jpg file set after migration
<img width="1163" alt="Screenshot 2024-10-25 at 1 21 19 PM" src="https://github.com/user-attachments/assets/70fd4923-df93-4676-b154-bb10f99c3189">

</details>
